version: "3.8"

networks:
  spring_boot_mysql_bridge: # 네트워크 이름 설정

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped # 컨테이너가 명시적으로 중지되지 않는 한 항상 재시작합니다
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - spring_boot_mysql_bridge

  app:
    depends_on:
      - mysqldb
    build: ./backend
    restart: on-failure # 컨테이너가 비정상적으로 종료되면 재시작합니다. 즉, 종료 코드가 0이 아닌 경우 재시작됩니다.
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD"
      }'
    networks:
      - spring_boot_mysql_bridge

volumes:
  db: