spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: create

  logging:
    level:
      root: DEBUG  